name: Debug Test

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Debug environment
        run: |
          echo "Node version: $(node --version)"
          echo "npm version: $(npm --version)"
          echo "Current directory: $(pwd)"
          echo "Files in project:"
          ls -la
          echo "Package.json contents:"
          cat package.json

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm ci
          echo "Dependencies installed successfully"

      - name: Test generator with minimal setup
        env:
          LLM_ENABLED: false
        run: |
          echo "Testing puzzle generator..."
          echo "Environment: LLM_ENABLED=$LLM_ENABLED"
          mkdir -p public/puzzles data
          npm run generate
          echo "Generation complete, checking output..."
          ls -la public/puzzles/
          if [ -f "public/puzzles/$(date +'%Y-%m-%d').json" ]; then
            echo "✅ Success: Puzzle file created"
            cat "public/puzzles/$(date +'%Y-%m-%d').json" | head -20
          else
            echo "❌ Failed: No puzzle file found"
            exit 1
          fi